#!/usr/bin/env bash
# Configure your domain zone

if [ $# -le 1 ]; then
    check_subdomain() {
        subdomain=$1
        dig "$subdomain.$2" | grep -A1 'ANSWER SECTION:' | awk -v subdomain="$subdomain" '{print "The subdomain " subdomain " is a " $4 " record and points to " $5 }' | tail -n 1
    }

    check_subdomain www "$1"
    check_subdomain lb-01 "$1"
    check_subdomain web-01 "$1"
    check_subdomain web-02 "$1"
else
    subdomain=$2
    echo -n "The subdomain $subdomain"
    dig "$subdomain.$1" | grep -A1 'ANSWER SECTION:' | awk -v subdomain="$subdomain" '{print " is a " $4 " record and points to " $5 }' | tail -n 1
fi